controller_list:
  - name: fake_left_controller
    joints:
      - left_joint_1_s
      - left_joint_2_l
      - left_joint_3_e
      - left_joint_4_u
      - left_joint_5_r
      - left_joint_6_b
      - left_joint_7_t
  - name: fake_right_controller
    joints:
      - right_joint_1_s
      - right_joint_2_l
      - right_joint_3_e
      - right_joint_4_u
      - right_joint_5_r
      - right_joint_6_b
      - right_joint_7_t
  - name: fake_torso_controller
    joints:
      - torso_joint_b1
      - torso_joint_b2
  - name: fake_arms_controller
    joints:
      - left_joint_1_s
      - left_joint_2_l
      - left_joint_3_e
      - left_joint_4_u
      - left_joint_5_r
      - left_joint_6_b
      - left_joint_7_t
      - right_joint_1_s
      - right_joint_2_l
      - right_joint_3_e
      - right_joint_4_u
      - right_joint_5_r
      - right_joint_6_b
      - right_joint_7_t
  - name: fake_bmda3_controller
    joints:
      - torso_joint_b1
      - left_joint_1_s
      - left_joint_2_l
      - left_joint_3_e
      - left_joint_4_u
      - left_joint_5_r
      - left_joint_6_b
      - left_joint_7_t
      - right_joint_1_s
      - right_joint_2_l
      - right_joint_3_e
      - right_joint_4_u
      - right_joint_5_r
      - right_joint_6_b
      - right_joint_7_t
      - torso_joint_b2