controller_list:
  - name: fake_arm_left_controller
    joints:
      - left_joint_s
      - left_joint_l
      - left_joint_e
      - left_joint_u
      - left_joint_r
      - left_joint_b
      - left_joint_t
  - name: fake_arm_right_controller
    joints:
      - right_joint_s
      - right_joint_l
      - right_joint_e
      - right_joint_u
      - right_joint_r
      - right_joint_b
      - right_joint_t
  - name: fake_torso_controller
    joints:
      - torso_joint_b1
      - torso_joint_b2
  - name: fake_arms_controller
    joints:
      - left_joint_s
      - left_joint_l
      - left_joint_e
      - left_joint_u
      - left_joint_r
      - left_joint_b
      - left_joint_t
      - right_joint_s
      - right_joint_l
      - right_joint_e
      - right_joint_u
      - right_joint_r
      - right_joint_b
      - right_joint_t
  - name: fake_bmda3_controller
    joints:
      - torso_joint_b1
      - left_joint_s
      - left_joint_l
      - left_joint_e
      - left_joint_u
      - left_joint_r
      - left_joint_b
      - left_joint_t
      - right_joint_s
      - right_joint_l
      - right_joint_e
      - right_joint_u
      - right_joint_r
      - right_joint_b
      - right_joint_t
      - torso_joint_b2